esbuild/config.js, package.json, pnpm-lock.yaml
Fixed error on create new CSSStyleSheet instance in safari by adding polyfill
=> fix: add cssstylesheet polyfill

idkit/src/components/IDKitWidget/States/WorldID/QRState.tsx
reuses code from https://github.com/worldcoin/world-id-sign-in/pull/45 to improve animation when clicking QR code to copy the link
old jarring animation:
https://github.com/worldcoin/idkit-js/assets/29718876/25871f88-c0eb-431a-a69b-ed7a82b3dd6f
new smooth animation:
https://github.com/worldcoin/idkit-js/assets/29718876/5ca98839-9ac4-4282-8828-21baf4583226
=> fix: qr code copied animation

packages/core/package.json, packages/core/src/bridge.ts, packages/react/package.json, packages/standalone/package.json
- If not provided, `credential_types` defaults to `[CredentialType.Orb]`
- Sets explicit privacy of packages as public.
=> feat: set package privacy & send `credential_types` by default

packages/core/src/bridge.ts, packages/react/src/components/IDKitWidget/States/WorldIDState.tsx, packages/react/src/store/idkit.ts
Resolves an issue I demo'd to @m1guelpf where IDKit would resubmit a proof to callback functions when it was reopened. The bridge store in `idkit-core` wasn't clearing the `result` and `errorCode` on reset, so these values were getting picked up again when entering `WorldIDState`.
Also adds proper error when a proof request times out (such as when a user never scans the QR code or never clicks "Verify with World ID" in the app). This is a distinct error from a user rejecting a proof request.
Also fixes an issue where if an error was thrown synchronously in `handleVerify`, the error would not be properly displayed by IDKit. Resolved by always calling `handleVerify` callbacks as async so the thrown error is handled as promise rejection.
Also ensures that the `credential_type` returned in …
=> feat: idkit state and error handling improvements

packages/core/src/bridge.ts, packages/core/src/lib/utils.ts, packages/core/src/types/result.ts, packages/react/src/components/IDKitWidget/States/WorldIDState.tsx
ISuccessResult now uses verification_level instead of credential_type. this handles conversion of returned credential_type from identity wallet to verification_level
=> feat: return verification_level instead of credential_type

packages/react/src/components/IDKitWidget/States/SuccessState.tsx
fixes the issue pictured above (only impacts shopify)
=> fix: width and centering text on success state

packages/react/src/components/IDKitWidget/States/WorldID/QRState.tsx
Adding an anchor will prevent the page from refreshing once you've confirmed with Idkit. Should also be fine for when you re use the same verification since it'll just add another anchor. See video below
https://github.com/worldcoin/idkit-js/assets/41224501/a14db6c5-b99d-4ae4-87b9-f14f39e8965e
=> fix: Redirect Links from App after Verification

packages/react/src/components/IDKitWidget/States/WorldID/QRState.tsx
Removes the default `return_to` value in IDKit. Resolves issues with UX on iOS where extra tabs or wrong browser may be opened.
=> fix: remove return_to

packages/core/src/bridge.ts, packages/core/src/lib/validation.ts
Validates `bridge_url` in `idkit-core`, fails verification and throws error if:
- not https
- non-default port defined
- has a path
- has query parameters
- has a fragment
Logs a non-blocking console warning if the `bridge_url` hostname does not end with `worldcoin.org` or `toolsforhumanity.com` -- to be removed once the restriction is lifted in World App.
Additionally, `idkit-core` now properly handles trailing slash. A `bridge_url` input as `...coin.org/` or `...coin.org` will both function properly.
=> feat: validate bridge_url

packages/react/src/components/IDKitWidget/States/ErrorState.tsx
uses a fixed px value for width of error message to prevent formatting errors when root font-size is changed
=> fix: error message width

packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
Zustand version was set to ^4.3.3, but we use `createWithEqualityFn` from `zustand/traditional`, which wasn't added until 4.4. Curiously, the lockfile had Zustand at 4.4.1.
Updating dependency version to ^4.5 (current latest minor release) resolves any potential dependency issues -- I have not run into it before (seems that usually Zustand 4.4 gets used?), but happened to get Zustand 4.3.x installed as a dependency in another project today and got the errors which this PR resolves.
Tested and working.
=> fix: bump zustand to ^4.5

packages/core/src/types/config.ts, packages/react/src/components/IDKitWidget/BaseWidget.tsx
requires the `action` prop to not be an empty string in IDKit react and standalone
=> feat: enforce non-empty string for action in IDKit

.github/workflows/release.yml
Update CI release v2 no longer works and release is failing as a result
=> ci: Update CI for release

.github/workflows/release.yml
Include github release in CI. Some of our internal CI fetches packages from github packages instead which causes errors
=> ci: Add github packages

packages/core/src/lib/utils.ts
Document versions were breaking since app tries to resolve credential types and iOS doesn't support them yet. Also adding @decentralgabe to CODEOWNERS
=> fix: idkit verification levels were off

packages/react/src/components/IDKitWidget/BaseWidget.tsx
Getting a client side error related to DialogContent not having DialogTitle when opening the base widget with the QR code. Error message is:
```
DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.
If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.
For more information, see https://radix-ui.com/primitives/docs/components/dialog
```
=> fix: client side error from no dialog title for accessibility

packages/core/src/lib/backend.ts
In Cloudflare worker environment, fetch doesn't have default 'User-Agent' setting for the `fetch`. 
Which results in below error. 
```
SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
at verifyCloudProof ([redacted]/@worldcoin_minikit-js.js:63707:33)
at Array.verify ([redacted]/packages/web/worker/endpoints/verify.ts:17:22)
```
The returned response is as following
```
Response {
status: 403,
statusText: 'Forbidden',
headers: Headers(5) {
'connection' => 'keep-alive',
'content-length' => '118',
'content-type' => 'text/html',
'date' => 'Sat, 10 May 2025 13:11:08 GMT',
'server' => 'awselb/2.0',
[immutable]: true
},
ok: false,
redirected: false,
url: 'https://developer.worldcoin.org/api/v2/verify/[redacted]',
webSocket: null,
cf: undefined,
type: 'default',
body: …
```
=> fix: add headers param to verifyCloudProof

packages/react/src/components/IDKitWidget/BaseWidget.tsx
Fix IDKit React. Title was in the wrong place
=> fix: IDKit React Title in wrong place

.changeset/famous-onions-refuse.md, packages/react/package.json, packages/react/tsup.config.ts
This PR fixes type declarations in `@worldcoin/idkit`. 
Refer here to see previous state: https://arethetypeswrong.github.io/?p=%40worldcoin%2Fidkit%402.2.0
=> fix: Support all type declarations

.changeset/bright-rocks-marry.md, packages/react/package.json, packages/react/src/components/IDKitWidget/BaseWidget.tsx, packages/react/src/components/IDKitWidget/ShadowHost.tsx, pnpm-lock.yaml
This PR replaces `react-shadow` dependency with a custom component. 
`react-shadow` caused problems with React v19 compatibility, and by replacing it with a custom component, it solved this issue. 
Completes DEV-1914.
=> build: Remove `react-shadow` depedency
