- README.md
- idkit/README.md
- idkit/src/types/Config.ts
We need to retouch these at some point, but this brings them up to date for launch.
> docs: Update basic docs

- idkit/src/index.ts
- Exports the main hashing functions so others can use them as utilities.
> feat: export main hashing functions

- idkit/src/components/SignInWithWorldID.tsx
> fix: Update SignInWithWorldID.tsx

- README.md
The getting started Readme doesnt seem to give the latest update so i change it to keep it updated.
> Fix Readme on the Getting Started

- example-nextjs/pages/index.tsx
- example-react/src/App.tsx
- idkit/src/index.ts
- idkit/src/store/idkit.ts
- idkit/src/types/config.ts
- idkit/src/vanilla.tsx
> feat: error handling

- README.md
adds instructions to develop locally to readme
> fix: update dev instructions in readme

- packages/react/package.json
- pnpm-lock.yaml
CI workflow failed so updating another outdated package to re-trigger
> build: update outdated packages

- examples/with-html/index.html
- packages/react/package.json
- packages/react/src/components/IDKitWidget/BaseWidget.tsx
- packages/react/src/components/IDKitWidget/States/WorldID/QRState.tsx
- packages/react/src/components/IDKitWidget/States/WorldIDState.tsx
- packages/standalone/src/index.tsx
- pnpm-lock.yaml
Introduces Close for Standalone: #257 
Exports isInitialized #256 
Improves UI for react to reduce overflow issues 
https://github.com/user-attachments/assets/9980bcb8-f024-46f3-81c2-339aab67c3e4
> feat: standalone improvements and widget mobile compatibility

- packages/react/src/components/IDKitWidget/BaseWidget.tsx
sets x button in modal to black by default
> fix: set x button to black

- examples/with-next/package.json
- pnpm-lock.yaml
> fix: upgrade next

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/relyance-sci.yml
- cspell.json
- examples/with-html/index.html
- package.json
- packages/core/package.json
- packages/core/src/lib/hashing.ts
- packages/core/tsup.config.ts
- packages/react/src/components/IDKitWidget/States/WorldID/QRState.tsx
- packages/react/src/components/IDKitWidget/States/WorldIDState.tsx
- packages/react/src/components/QRCode.tsx
- packages/react/src/lang/index.ts
- packages/react/tsup.config.ts
- pnpm-lock.yaml
- turbo.json
[ox](https://oxlib.sh/) is a lean standard library for Ethereum, built by the team behind viem.
> feat: switch to ox

- packages/core/src/lib/utils.ts
- packages/core/src/types/config.ts
add passport and secure passport
> feat: introduce new credential types

- packages/core/src/lib/utils.ts
- packages/core/src/types/config.ts
Add new credential types to idkit
> feat: Add new credential types

- .github/workflows/release.yml
- CODEOWNERS
- packages/core/package.json
- packages/react/package.json
- packages/standalone/package.json
Fixing a few issues with ci
1. Inconsistent package version
2. NO Code owners
3. Not specified "publishConfig": {"access": "public"}
version: 9.12.2
> fix: versioning and add CODEOWNERS

- CODEOWNERS
Forgot to add gabe to codeowners
> Add gabe to codeowners

- packages/core/src/bridge.ts
- packages/core/src/types/config.ts
IDKit add optional partner param that will redirect on company website to the join screen with the idkit params
completes ID-194
> Update with partner

- .github/workflows/release.yml
- packages/core/src/lib/utils.ts
> fix: trigger release please

- README.md
- packages/core/package.json
- packages/core/src/bridge.ts
- packages/core/src/types/config.ts
- packages/react/package.json
- packages/react/src/components/IDKitWidget/BaseWidget.tsx
- packages/react/src/components/IDKitWidget/States/ErrorState.tsx
- packages/standalone/package.json
Update the domains to new company domains
> fix: update domains to new company domains

- packages/react/package.json
- packages/react/src/components/IDKitWidget/States/WorldIDState.tsx
- packages/react/src/services/wld-bridge.ts
- packages/react/src/store/idkit.ts
- pnpm-lock.yaml
Partner was actually not being fully passed through the stores. In addition bump react-shadow as old version causes issues on next 15
> fix: partner being passed through

- examples/with-html/index.html
- examples/with-next/pages/index.tsx
- packages/core/src/lib/utils.ts
- packages/react/src/components/IDKitWidget/BaseWidget.tsx
- packages/react/src/components/IDKitWidget/States/WorldIDState.tsx
- packages/react/src/hooks/useMedia.ts
- packages/react/src/types/config.ts
Idkit improvements
1. Allow non dismissible modal
2. Update some copy to not dismiss
3. Make accessibility compatible
4. Fix the responsiveness and bump z
> fix: idkit-improvements

- packages/react/src/components/IDKitWidget/BaseWidget.tsx
- packages/react/src/components/IDKitWidget/States/WorldID/QRState.tsx
- packages/react/src/components/IDKitWidget/States/WorldIDState.tsx
Small Copy Changes that didn't make it into the main release only was in staging
> Copy Changes

- .changeset/version-1.5.0.md
- packages/core/package.json
- packages/core/src/bridge.ts
- packages/core/src/index.ts
- packages/core/src/lib/adapters/crypto-adapter.ts
- packages/core/src/lib/adapters/react-native-crypto-adapter.ts
- packages/core/src/lib/adapters/web-crypto-adapter.ts
- packages/core/src/lib/crypto.ts
- packages/core/src/lib/platform.ts
- packages/react-native/.eslintrc.cjs
- packages/react-native/README.md
- packages/react-native/package.json
- packages/react-native/src/index.ts
- packages/react-native/src/session.ts
- packages/react-native/tsconfig.json
- packages/react-native/tsup.config.ts
- pnpm-lock.yaml
Core library:
- Add crypto adapter that dynamically chooses between web and RN crypto API
- Optional peer dependencies for `react-native-quick-crypto`
- Refactor bridge and expose a store factory to allow for transient sessions 
React Native client:
- Adopt session pattern similar to https://github.com/worldcoin/idkit-swift
> feat: Support React Native for 1.x

- .changeset/happy-mirrors-train.md
Forgot to add in https://github.com/worldcoin/idkit-js/pull/336
> build: Add changeset to publish idkit react hotifx

- .changeset/floppy-olives-joke.md
- examples/with-next/pages/index.tsx
- packages/react/src/components/IDKitWidget/States/WorldID/QRState.tsx
- packages/react/src/hooks/useMedia.ts
Improve mobile changes.
1. Ipad not showing the button properly to redirect
2. Update the example with some scrolling so it's easier to test if the scroll view is being broken
https://github.com/user-attachments/assets/7e1748cc-2775-423a-82a2-af905f2a331a
> fix: mobile rendering
